### ISSUE TITLE
Query Regarding Code Release Schedule

### ISSUE THREAD

**Issue by lichencan** [Tommy-Bie/MICA#1]
I've been following your project with great interest and am impressed by the work you've accomplished so far.
Could you kindly provide any information regarding the planned release date or the current status of the code?

**Comment by Tommy-Bie** [comment]
Thank you for your interest in our work. Since we are currently focusing on other work, we may not be able to release the complete code too early. But we will try our best to get it done before the meeting takes place. Thanks again for your appreciation of our work :blush:.
