### ISSUE TITLE
Issues Regarding the “dataset” and “constant” Folders

### ISSUE THREAD

**Issue by chenYuL-Lin** [Tommy-Bie/MICA#2]
I have always been interested in your project, but I encountered some problems during the reproduction process. Due to the missing important "dataset" folder, the code cannot run in its entirety. Could you please provide a schedule for publishing relevant files and supplementing readme time?

**Comment by Tommy-Bie** [comment]
Thank you for your attention to our work. We will update the experimental details once we have completed what we have at hand.  Thank you again for your appreciation.
