### ISSUE TITLE
Incomplete Code

### ISSUE THREAD

**Issue by JetWings** [Tommy-Bie/MICA#3]
I've been following your project with great interest and am impressed by the work you've accomplished so far.
However, due to the incomplete code, it cannot be executed, for example, without files such as ViT and .yaml.

**Comment by Tommy-Bie** [comment]
Thanks for your interest in our work. We will update more details and refactor the code once we have completed what we have at hand.

**Comment by slmases** [comment]
Hi @Tommy-Bie I am very much interested in this project. But I am unable to execute this codes due to missing file ViT.py. Will you be uploading the pending files soon?
