### ISSUE TITLE
Question About CAV in MICA

### ISSUE THREAD

**Issue by fly-p** [Tommy-Bie/MICA#5]
Hello, I am very interested in the MICA project, but when reviewing the code, I noticed that you haven't provided a specific dataset, and I'm particularly unclear about the meaning of the 'report' column. Does it represent the symptoms (concepts) associated with each image? Will there be an upload of the dataset in the future?.Thank you for your time and assistance

**Comment by Tommy-Bie** [comment]
Thanks for your interest in our work. Yes, the 'report' column is actually a sentence that combines all the concepts (symptoms) of the image, e.g., "irregular streaks, blue whitish veil, regular vascular structures." You can easily add this column to the original meta csv file.
